class TimeConstants:
    PORTFOLIO_UPDATE_INTERVAL_MINUTES = 5
    DEFAULT_TIMEFRAME = "1h"
    DEFAULT_CANDLE_LIMIT = 100


class RiskConstants:
    DEFAULT_MAX_POSITION_SIZE_PCT = 0.1
    DEFAULT_MAX_TOTAL_EXPOSURE_PCT = 0.5
    DEFAULT_STOP_LOSS_PCT = 0.05
    DEFAULT_TAKE_PROFIT_PCT = 0.1
    DEFAULT_MAX_DRAWDOWN_PCT = 0.2
    DEFAULT_MAX_DAILY_LOSS_PCT = 0.03
    DEFAULT_MAX_OPEN_ORDERS = 10


class BacktestConstants:
    DEFAULT_INITIAL_CAPITAL = 10000
    DEFAULT_COMMISSION = 0.001
    DEFAULT_SLIPPAGE = 0.0005
    DEFAULT_POSITION_SIZE_PCT = 0.95


class TradingConstants:
    DEFAULT_EXCHANGE = "binance"
    DEFAULT_SYMBOL = "BTC/USDT"
    DEFAULT_MARKET_TYPE = "spot"
